# Generated by Django 5.0.6 on 2024-05-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycontroller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userabsentrequestdata',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
